### ISSUE TITLE
v0.3 ConvertXYZtoYUV crashes AVS

### ISSUE THREAD

**Issue by quietvoid** [jpsdr/HDRTools#2]
Hi, 
Since 0.3 I'm experiencing frequent crashes in AvsPmod when refreshing the preview.
It is fine with a build from commit https://github.com/jpsdr/HDRTools/commit/3cfa030dbdb571463d35eb68376b9298735e25ea and 0.2
So something between that and 0.3 is causing the crashing with ConvertXYZtoYUV.

It seems to be only crashing when using ConvertXYZtoYUV(pColor=1), the rest of the conversions are not crashing AvsPmod.
Using x64 AVX2 build, but it happens with non-AVX too.

Script that crashes
>FFVideoSource("sample.mkv", colorspace="YUV420P16")
>ConvertYUVtoXYZ(Color=1)
>ConvertXYZtoYUV(pColor=1) <- Crashes with this

I can reproduce the crashes when loading a frame, then going to the next frame or the same and refreshing the preview (F5 or Video > Refresh preview)

Also crashes when pre-scanning with AVSMeter, while ConvertYUVtoXYZ alone makes it to the frame processing.

Thanks

**Comment by jpsdr** [comment]
I'll try to look into it when i have time, don't have right now and can't test, not on my PC video. To help me narrow the issue : 
- Is it reproduçable also with VirtualDub 2 ? (I don't have and don't use AvsPmod, i stil can try to get it, but if issue also happens with VirtualDub 2, it will speed things up).
- Is it x64 specific, or does it also happens with x86 version ? (this information will help me to figure out on what part of the code the issue may come from).

**Comment by quietvoid** [comment]
Indeed it only crashes with x64 builds, x86 is fine.

I just tested on VirtualDub 2 x64 and it crashes as well. This is what I did to reproduce:
1. Loaded AVS script with Script Editor:
>FFVideoSource("sample.mkv", colorspace="YUV420P10")
>ConvertYUVtoXYZ(Color=1)
>ConvertXYZtoYUV(pColor=1)

Saved & opened as AVI. This doesn't crash and shows proper output.

2. Changed current showing frame by clicking/seeking on the timeline.
3. Saved & refresh the same script again without changing anything, this crashes VirtualDub 2.

With VirtualDub 2 x86, it fails loading the script after changing current frame, just with source filter.
But still shows old script output and allows seeking.

Both Release_W7 and Release_W7_AVX2 crash VirtualDub 2 with ConvertXYZtoYUV.

**Comment by jpsdr** [comment]
x86 fine and x64 crash => It's in ASM code. More complicated, because often in these cases, only people with Windows 10 trig it, when on my side with Windows 7 i don't trig it. On the other side, in these cases, issue is always the same ; i've forgotten somewhere to pass from 32 bits to 64 bits an address register. I'll test again later, but i was surprised as even if i may have missed some specific case, i made several tests and i'm sure i've tested this configuration case... Are you under Windows 10 ?

**Comment by jpsdr** [comment]
I'm not able to trig the issue in "standard" use/configuration (this is why i didn't see it). But, i've nevertheless tried to run under debuger a debug build version, in case in this configuration something happened. Furtunately, something happened, and i may i've found something. The x86/x64 difference behavior was just "luck" finaly. I think i may be able to make a new release in several hours.

**Comment by quietvoid** [comment]
Yep I am on Windows 10.
Cheers.

**Comment by jpsdr** [comment]
New version, can you tell me if it fixes your issue ?

**Comment by quietvoid** [comment]
Yes it does, this can be closed.
Thank you.
