### ISSUE TITLE
Add Support for Report ITU-R BT.2446-0

### ISSUE THREAD

**Issue by george84** [jpsdr/HDRTools#5]
This year in April was published Report ITU-R BT.2446-0 which describes 

> Methods for conversion of high dynamic range content to standard dynamic range content and vice-versa

As this is some kind of standard it would be nice to support it. I would be interested in proposed SDR->HDR conversion, but without writing code it cannot be used in avisynth.

**Comment by jpsdr** [comment]
Thanks for the information.
I've take a quick look, big thanks, it's very interesting, i'm very interested, but don't have time right now. So i'll do something with this, for sure !! But not soon, not before some months unfortunately.
But i will !!! ^_^

**Comment by musicrainie** [comment]
Looking forward to your excellent work.

**Comment by jpsdr** [comment]
Thanks. I hope i'll have time to make a new build soon.

**Comment by musicrainie** [comment]
Could you please provide an example to show the process of SDR to HDR  conversion of BT2446 in ReadMe?

**Comment by jpsdr** [comment]
I can't because i've only implemented HDR to SDR. I'm not interested (at least for now) in SDR to HDR, so i don't intend to implement SDR to HDR (again, at least for now).
